[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "controlmanual"
version = "1.0.0"

[project.urls]
source = "https://github.com/ZeroIntensity/controlmanual"
