#ifndef CM_VERSION_H
#define CM_VERSION_H

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define VERSION_MAJOR 0
#define VERSION_MINOR 0
#define VERSION_PATCH 0
#define VERSION_MICRO VERSION_PATCH
#define VERSION_RELEASE "alpha"
#define VERSION_RELEASE_NUM 0
#define VERSION_STR STR(VERSION_MAJOR) "." STR(VERSION_MINOR) "." STR(VERSION_PATCH)
#define VERSION_FULL VERSION_STR "-" VERSION_RELEASE "." STR(VERSION_RELEASE_NUM)

#endif